import type { GradeOption, GradeKey, SharedTagDefinition, ViewOption } from "@/types";

export const GRADE_OPTIONS: GradeOption[] = [
  { id: "all", label: "Escola", shortLabel: "Escola", accent: "#7dd3fc" },
  { id: "6", label: "6º ano", shortLabel: "6º", accent: "#67e8f9" },
  { id: "7", label: "7º ano", shortLabel: "7º", accent: "#f9a826" },
  { id: "8", label: "8º ano", shortLabel: "8º", accent: "#fb7185" },
  { id: "9", label: "9º ano", shortLabel: "9º", accent: "#34d399" },
  { id: "maker", label: "Maker", shortLabel: "Maker", accent: "#facc15" },
];

export const VIEW_OPTIONS: ViewOption[] = [
  { id: "overview", label: "Overview", helper: "Sinais gerais e prioridades." },
  { id: "students", label: "Students", helper: "Pessoas, grupos e relações." },
  { id: "classes", label: "Classes", helper: "Pulso de cada turma." },
  { id: "teachers", label: "Teachers", helper: "Carga, distribuição e alcance." },
  { id: "schedule", label: "Schedule", helper: "Timetable, ritmo e gargalos." },
  { id: "insights", label: "Insights", helper: "Alertas e decisões pedagógicas." },
  {
    id: "interdisciplinary",
    label: "Interdisciplinary",
    helper: "Mapa vivo de conexões curriculares.",
  },
];

export const DAYS = ["Seg", "Ter", "Qua", "Qui", "Sex"];

export const TIME_SLOTS = [
  "07:30",
  "08:15",
  "09:00",
  "09:45",
  "11:00",
  "11:45",
  "12:30",
  "14:15",
  "15:00",
  "15:45",
  "16:30",
];

export interface SubjectDefinition {
  id: string;
  label: string;
  shortLabel: string;
  domain: string;
  color: string;
  aliases: string[];
  scheduleCodes: string[];
  relatedSubjectIds?: string[];
}

export const SUBJECT_CATALOG: SubjectDefinition[] = [
  {
    id: "matematica",
    label: "Matemática",
    shortLabel: "MAT",
    domain: "Lógico-analítico",
    color: "#67e8f9",
    aliases: ["matematica", "mat", "math", "ib math"],
    scheduleCodes: ["MAT"],
  },
  {
    id: "ciencias",
    label: "Ciências",
    shortLabel: "CIE",
    domain: "Investigação científica",
    color: "#2dd4bf",
    aliases: ["ciencias", "ciencia", "cie"],
    scheduleCodes: ["CIE"],
  },
  {
    id: "quimica",
    label: "Química",
    shortLabel: "QUI",
    domain: "Investigação científica",
    color: "#14b8a6",
    aliases: ["quimica", "química"],
    scheduleCodes: ["QUI"],
    relatedSubjectIds: ["ciencias"],
  },
  {
    id: "geografia",
    label: "Geografia",
    shortLabel: "GEO",
    domain: "Território & sociedade",
    color: "#f59e0b",
    aliases: ["geografia", "geo"],
    scheduleCodes: ["GEO"],
  },
  {
    id: "historia",
    label: "História",
    shortLabel: "HIS",
    domain: "Território & sociedade",
    color: "#fb7185",
    aliases: ["historia", "história", "his"],
    scheduleCodes: ["HIS"],
  },
  {
    id: "ingles",
    label: "Inglês",
    shortLabel: "ING",
    domain: "Linguagens",
    color: "#38bdf8",
    aliases: ["ingles", "inglês", "ing"],
    scheduleCodes: ["ING"],
  },
  {
    id: "espanhol",
    label: "Espanhol",
    shortLabel: "ESP",
    domain: "Linguagens",
    color: "#f97316",
    aliases: ["espanhol", "esp"],
    scheduleCodes: ["ESP"],
  },
  {
    id: "lingua-portuguesa",
    label: "Língua Portuguesa",
    shortLabel: "LP",
    domain: "Linguagens",
    color: "#f472b6",
    aliases: ["lingua portuguesa", "língua portuguesa", "portugues", "português", "lp"],
    scheduleCodes: ["LP"],
  },
  {
    id: "redacao",
    label: "Redação",
    shortLabel: "RED",
    domain: "Linguagens",
    color: "#fb7185",
    aliases: ["redacao", "redação", "red1", "red2"],
    scheduleCodes: ["RED1", "RED2", "RED"],
  },
  {
    id: "literatura-projetos",
    label: "Literatura & Projetos",
    shortLabel: "LIT",
    domain: "Linguagens",
    color: "#a3e635",
    aliases: ["literatura", "lit pr", "lit pr.", "literatura e projetos"],
    scheduleCodes: ["LIT PR", "LIT PR"],
  },
  {
    id: "educacao-fisica",
    label: "Educação Física",
    shortLabel: "EDF",
    domain: "Corpo & movimento",
    color: "#fb923c",
    aliases: ["educacao fisica", "educação física", "edf"],
    scheduleCodes: ["EDF"],
  },
  {
    id: "maker",
    label: "Maker",
    shortLabel: "MAK",
    domain: "Tecnologia & criação",
    color: "#facc15",
    aliases: ["maker", "inovacao e criacao", "inovação e criação", "stem"],
    scheduleCodes: ["MK", "MAKER"],
  },
  {
    id: "teatro",
    label: "Teatro",
    shortLabel: "TEA",
    domain: "Arte & expressão",
    color: "#ef4444",
    aliases: ["teatro", "tea"],
    scheduleCodes: ["TEA"],
  },
  {
    id: "maker-teatro",
    label: "Maker / Teatro",
    shortLabel: "MK-TEA",
    domain: "Tecnologia & criação",
    color: "#fde047",
    aliases: ["mk-tea", "maker teatro", "maker / teatro"],
    scheduleCodes: ["MK-TEA"],
    relatedSubjectIds: ["maker", "teatro"],
  },
  {
    id: "artes",
    label: "Artes",
    shortLabel: "ART",
    domain: "Arte & expressão",
    color: "#f97316",
    aliases: ["artes", "artes visuais", "art"],
    scheduleCodes: ["ART"],
  },
  {
    id: "musica",
    label: "Música",
    shortLabel: "MUS",
    domain: "Arte & expressão",
    color: "#e879f9",
    aliases: ["musica", "música", "mus"],
    scheduleCodes: ["MUS"],
  },
  {
    id: "projeto-de-vida",
    label: "Projeto de Vida",
    shortLabel: "PV",
    domain: "Formação integral",
    color: "#34d399",
    aliases: ["pv", "projeto de vida"],
    scheduleCodes: ["PV"],
  },
  {
    id: "orientacao-de-estudos",
    label: "Orientação de Estudos",
    shortLabel: "OE",
    domain: "Formação integral",
    color: "#60a5fa",
    aliases: ["oe", "orientacao de estudos", "orientação de estudos"],
    scheduleCodes: ["OE"],
  },
  {
    id: "educacao-financeira",
    label: "Educação Financeira",
    shortLabel: "EFI",
    domain: "Formação integral",
    color: "#10b981",
    aliases: ["educacao financeira", "educação financeira"],
    scheduleCodes: ["EFI"],
  },
];

export const SHARED_TAGS: SharedTagDefinition[] = [
  {
    id: "analise-de-dados",
    label: "Análise de Dados",
    description: "Leitura, representação e interpretação de informações.",
    color: "#67e8f9",
    keywords: [
      "dados",
      "grafico",
      "gráfico",
      "estatistica",
      "estatística",
      "tabela",
      "medicao",
      "medição",
      "indicadores",
      "visualizacao",
      "visualização",
      "interpretar",
      "analise",
      "análise",
      "probabilidade",
    ],
    complementary: ["sistemas-urbanos", "sustentabilidade", "pensamento-computacional"],
  },
  {
    id: "sustentabilidade",
    label: "Sustentabilidade",
    description: "Relações socioambientais, recursos e futuro compartilhado.",
    color: "#34d399",
    keywords: [
      "sustentabilidade",
      "ambiental",
      "residuos",
      "resíduos",
      "reciclagem",
      "agua",
      "água",
      "esgoto",
      "energia",
      "biodiversidade",
      "ecossistema",
      "planeta",
      "socioambiental",
      "poluentes",
    ],
    complementary: ["prototipagem-digital", "sistemas-urbanos", "cidadania-e-etica"],
  },
  {
    id: "sistemas-urbanos",
    label: "Sistemas Urbanos",
    description: "Cidade, mobilidade, território e infraestrutura.",
    color: "#f59e0b",
    keywords: [
      "cidade",
      "urbano",
      "urbanizacao",
      "urbanização",
      "mobilidade",
      "territorio",
      "território",
      "infraestrutura",
      "bairro",
      "paisagem",
      "espaco urbano",
      "espaço urbano",
      "mapa",
    ],
    complementary: ["analise-de-dados", "sustentabilidade", "comunicacao-e-narrativa"],
  },
  {
    id: "pensamento-geometrico",
    label: "Pensamento Geométrico",
    description: "Forma, espaço, escala, proporção e visualização.",
    color: "#38bdf8",
    keywords: [
      "geometria",
      "area",
      "área",
      "perimetro",
      "perímetro",
      "solidos",
      "sólidos",
      "volume",
      "escala",
      "medidas",
      "espacial",
      "mapa",
      "forma",
    ],
    complementary: ["prototipagem-digital", "expressao-artistica", "analise-de-dados"],
  },
  {
    id: "investigacao-cientifica",
    label: "Investigação Científica",
    description: "Experimentos, hipóteses, observação e validação.",
    color: "#2dd4bf",
    keywords: [
      "experimento",
      "investigar",
      "hipotese",
      "hipótese",
      "observacao",
      "observação",
      "microscopio",
      "microscópio",
      "teoria",
      "classificar",
      "analisar",
      "coleta",
      "evidencia",
      "evidência",
    ],
    complementary: ["analise-de-dados", "prototipagem-digital", "saude-e-corpo"],
  },
  {
    id: "prototipagem-digital",
    label: "Prototipagem Digital",
    description: "Programação, modelagem, eletrônica e fabricação.",
    color: "#facc15",
    keywords: [
      "arduino",
      "programacao",
      "programação",
      "algoritmo",
      "3d",
      "modelagem",
      "prototipo",
      "protótipo",
      "eletronicos",
      "eletrônicos",
      "componentes",
      "hardware",
      "software",
      "solucoes digitais",
      "soluções digitais",
    ],
    complementary: ["sustentabilidade", "pensamento-geometrico", "analise-de-dados"],
  },
  {
    id: "pensamento-computacional",
    label: "Pensamento Computacional",
    description: "Decomposição, padrões, abstração e resolução de problemas.",
    color: "#a3e635",
    keywords: [
      "decompor",
      "padroes",
      "padrões",
      "abstrair",
      "resolver problemas",
      "depurar",
      "testar",
      "logica",
      "lógica",
      "sequencia",
      "sequência",
      "dados estruturados",
    ],
    complementary: ["analise-de-dados", "prototipagem-digital", "investigacao-cientifica"],
  },
  {
    id: "comunicacao-e-narrativa",
    label: "Comunicação & Narrativa",
    description: "Leitura, escrita, argumentação e oralidade.",
    color: "#f472b6",
    keywords: [
      "argumentacao",
      "argumentação",
      "leitura",
      "escrita",
      "texto",
      "oralidade",
      "debate",
      "narrativa",
      "redacao",
      "redação",
      "apresentar",
      "linguagens",
    ],
    complementary: ["sistemas-urbanos", "expressao-artistica", "cidadania-e-etica"],
  },
  {
    id: "expressao-artistica",
    label: "Expressão Artística",
    description: "Criação visual, sonora, corporal e performática.",
    color: "#fb7185",
    keywords: [
      "musica",
      "música",
      "arte",
      "artistica",
      "artística",
      "teatro",
      "performance",
      "imagem",
      "som",
      "ritmo",
      "corporal",
      "cultural",
    ],
    complementary: ["comunicacao-e-narrativa", "pensamento-geometrico", "sistemas-urbanos"],
  },
  {
    id: "cidadania-e-etica",
    label: "Cidadania & Ética",
    description: "Consciência crítica, direitos, cuidado coletivo e convivência.",
    color: "#60a5fa",
    keywords: [
      "cidadania",
      "etica",
      "ética",
      "direitos",
      "consumo",
      "democratica",
      "democrática",
      "responsabilidade",
      "convivencia",
      "convivência",
      "respeito",
      "sociedade",
    ],
    complementary: ["sustentabilidade", "comunicacao-e-narrativa", "saude-e-corpo"],
  },
  {
    id: "saude-e-corpo",
    label: "Saúde & Corpo",
    description: "Movimento, percepção, equilíbrio e cuidado com si e com o outro.",
    color: "#fb923c",
    keywords: [
      "saude",
      "saúde",
      "corpo",
      "movimento",
      "sensorial",
      "equilibrio",
      "equilíbrio",
      "esporte",
      "papilas",
      "sistema nervoso",
      "olfato",
      "gustacao",
      "gustação",
      "visao",
      "visão",
      "audicao",
      "audição",
    ],
    complementary: ["investigacao-cientifica", "cidadania-e-etica", "expressao-artistica"],
  },
];

export function isGradeMatch(gradeKeys: GradeKey[], activeGrade: GradeKey) {
  if (activeGrade === "all") {
    return true;
  }
  return gradeKeys.includes(activeGrade) || gradeKeys.includes("all");
}

